all: d4.sif mctw.sif sharpSAT.sif spur.sif unigen3.sif

d4.sif:
	singularity build --fakeroot d4.sif d4.def

mctw.sif:
	singularity build --fakeroot mctw.sif mctw.def

sharpSAT.sif:
	singularity build --fakeroot sharpSAT.sif sharpSAT.def

spur.sif:
	singularity build --fakeroot spur.sif spur.def

unigen3.sif:
	singularity build --fakeroot unigen3.sif unigen3.def
